#!/bin/tcsh
    ### myBatchSubmit
    ### LSF syntax
    #BSUB -nnodes 2                   #number of nodes
    #BSUB -W 100                       #walltime in hours:minutes
    #BSUB -G orsu                     #account
    #BSUB -e pysweep-log-2.txt              #stderr
    #BSUB -o pysweep-out-2.txt              #stdout
    #BSUB -J pysweep-2               #name of job
    #BSUB -q pbatch                   #queue to use

    ### Shell scripting
    hostname
    echo -n 'JobID is '; echo $LSB_JOBID
    
    conda activate pysweep-dev
    
    ### Launch parallel executable
    echo 'Launching executable...'
    echo 'Time at computation start:'
    date
    echo ' '
    
    jsrun -n2 -r1 -a40 -c40 -g1pysweep -f euler -nx 500 -nt 100 -b 16 -s 1 --swept --verbose --ignore --clean

    jsrun -n2 -r1 -a40 -c40 -g1 pysweep -f euler -nx 500 -nt 100 -b 16 -s 1 --verbose --ignore --clean

    echo 'Time at computation finish:'
    date
    echo 'Done'
    
    